name: parrot_head_flutter_tutorial
description: "A sample app showing how GraphQL can work with Freezed and Riverpod."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  graphql_flutter: ^5.1.2
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.18.4
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.1.0
  json_annotation: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  custom_lint: ^0.6.4 
  riverpod_generator: ^2.3.4
  riverpod_lint: ^2.2.0
  analyzer: ^6.4.0
  freezed: ^2.1.0
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
